# Allows the running of the site in a subdirectory on Github Pages
# Note - if you enable this, and attempt to view your site locally you have to 
# pass the  --baseurl parameter when serving as an empty string e.g jekyll serve --baseurl ''
# http://jekyllrb.com/docs/github-pages/
baseurl : ""
relative_permalinks: false

# Name of the website
name: "ImageProcessor"
altname : "ImageProcessor.Web"

# Short description (goes below the title)
description: "A C# library for the dynamic processing of image files with .NET. ImageProcessor can resize, rotate, crop, flip, fade, watermark and add Instagram style filters to images."

# Your name, as you want it to appear underneath each post and in the footer
author: "James South"

version: "2.1.0"
webversion: "4.1.0"
configversion: "2.1.0"

# Set variables by folder rather than individually.
defaults:
# ===================================================
# ImageProcessor
# ===================================================
  -
    scope:
      path: "imageprocessor"
    values:
      navgroup: imageprocessor
      layout: library
      root: ImageProcessor # Allows the root page to list all classes.
  -
    scope:
      path: "imageprocessor/imagefactory"
    values:
      layout: method
      heading: Methods
      methodof: ImageFactory # Adds the method to the class page.
  -
    scope:
      path: "imageprocessor/imagefactory/index.html"
    values:
      layout: class
  -
    scope:
      path: "imageprocessor/nativebinaryfactory"
    values:
      layout: method
      heading: Methods
      methodof: NativeBinaryFactory # Adds the method to the class page.
  -
    scope:
      path: "imageprocessor/nativebinaryfactory/index.html"
    values:
      layout: class

# ===================================================
# ImageProcessor.Web
# ===================================================
  -
    scope:
      path: "imageprocessor-web"
    values:
      navgroup: imageprocessorweb
      layout: library
      root: ImageProcessorWeb
  -
    scope:
      path: "imageprocessor-web/imageprocessingmodule"
    values:
      navgroup: imageprocessorweb
      layout: method
      heading: Methods
      methodof: ImageProcessingModule
  -
    scope:
      path: "imageprocessor-web/imageprocessingmodule/index.html"
    values:
      layout: class

exclude: ["CNAME","src","node_modules","Gemfile","Gemfile.lock"]